### ISSUE TITLE
Name of package is non obvious 

### ISSUE THREAD

**Issue by toplenboren** [arty-name/martian-cidr#50]
Hi! Thanks for your work!

Really like your package :-) but I think the name `isMartian` is not really obvious.. You have to explain what a martian packet is every time you use it.. 

I think calling library `isReservedIp(ip)` might be more obvious for end user

What do you think?

**Comment by arty-name** [comment]
Thank you for your kind words!

Since the package doesn’t use named export, you can use any name you like for the imported function.

```js
import isMartianIP from 'martian-cidr'; // suggested in the readme
import isReservedIp from 'martian-cidr'; // feel free to import it like this instead
```

Would that work for you?

**Comment by toplenboren** [comment]
Yep, this might work for me :-) thanks for the prompt response!

**Comment by arty-name** [comment]
Sweet! I’ll mark it as resolved then.
